"""
Wiring + unit tests for SceneForge modules.

These tests deliberately do NOT run COLMAP or OpenSplat to completion --
that's covered by manual integration testing (see docs/test_log.md).
Instead they verify:
  1. Every module imports cleanly and exposes its documented API.
  2. Fetcher/validator/viewer behave correctly on real sample data
     (assets/test_images, generated by scripts/generate_test_scene.py).
  3. Error paths raise the correct, documented exception types.
  4. The orchestrator correctly chains stages in order (proven by the
     fact that it reaches the LAST stage's error, not an earlier one).
"""
from __future__ import annotations

import shutil
import tempfile
from pathlib import Path

import pytest

from sceneforge import colmap_runner, engine, fetcher, orchestrator, validator, viewer

TEST_IMAGES_DIR = Path(__file__).parent.parent / "assets" / "test_images"


# --- fetcher -----------------------------------------------------------

def test_fetcher_finds_sample_images():
    records = fetcher.fetch_from_folder(TEST_IMAGES_DIR)
    assert len(records) > 0
    assert all(r.path.suffix.lower() in fetcher.SUPPORTED_EXTENSIONS for r in records)
    assert all(r.width > 0 and r.height > 0 for r in records)


def test_fetcher_raises_on_missing_folder():
    with pytest.raises(fetcher.FetchError):
        fetcher.fetch_from_folder("/this/path/does/not/exist")


def test_fetcher_raises_on_empty_folder():
    with tempfile.TemporaryDirectory() as tmp:
        with pytest.raises(fetcher.FetchError):
            fetcher.fetch_from_folder(tmp)


# --- validator -----------------------------------------------------------

def test_validator_passes_sufficient_images():
    records = fetcher.fetch_from_folder(TEST_IMAGES_DIR)
    report = validator.validate(records)
    assert report.image_count == len(records)
    assert report.passed is True
    assert report.rejected == []


def test_validator_warns_on_too_few_images():
    records = fetcher.fetch_from_folder(TEST_IMAGES_DIR)[:3]  # below MIN_IMAGE_COUNT
    report = validator.validate(records)
    assert report.passed is False
    assert any("recommend" in w for w in report.warnings)


# --- colmap_runner -----------------------------------------------------------

def test_colmap_binary_is_discoverable():
    # This environment has colmap installed via apt; assert the wrapper
    # can find it (raises ColmapNotFoundError otherwise).
    binary = colmap_runner._require_colmap()
    assert binary  # non-empty path string


def test_colmap_runner_raises_clean_error_when_binary_missing(monkeypatch):
    monkeypatch.setattr(shutil, "which", lambda name: None)
    with pytest.raises(colmap_runner.ColmapNotFoundError):
        colmap_runner._require_colmap()


# --- engine -----------------------------------------------------------

def test_engine_raises_clean_error_when_opensplat_missing():
    # opensplat is NOT installed in this environment (requires building
    # from source with libtorch) -- confirm the failure is the documented
    # OpenSplatNotFoundError, not a generic crash.
    with pytest.raises(engine.OpenSplatNotFoundError):
        engine._resolve_binary(None)


# --- viewer -----------------------------------------------------------

def test_viewer_generates_valid_html(tmp_path):
    html_path = viewer.generate_viewer_html(
        splat_path=tmp_path / "splat" / "splat.ply",
        output_html=tmp_path / "viewer.html",
        title="Test Scene",
    )
    assert html_path.exists()
    content = html_path.read_text()
    assert "SplatMesh" in content
    assert "sparkjs" in content
    assert "Test Scene" in content


# --- orchestrator wiring -----------------------------------------------------------

def test_orchestrator_chains_stages_in_order(tmp_path):
    """
    Confirms fetcher -> validator -> colmap_runner -> engine -> viewer
    are wired in the correct order. We don't have opensplat installed,
    so the pipeline is EXPECTED to fail at the engine stage -- reaching
    that exact failure point (not an earlier one) proves COLMAP's real
    SfM stage executed successfully against our sample images first.
    """
    with pytest.raises(engine.OpenSplatNotFoundError):
        orchestrator.run_pipeline(
            images_dir=TEST_IMAGES_DIR,
            output_dir=tmp_path,
            iterations=5,
        )

    # If COLMAP actually ran (proving it's not a wiring/skip bug), its
    # sparse model files should exist on disk at this point.
    sparse_dir = tmp_path / "colmap" / "sparse" / "0"
    assert (sparse_dir / "images.bin").exists()
    assert (sparse_dir / "points3D.bin").exists()


def test_orchestrator_cli_help_works():
    from typer.testing import CliRunner
    runner = CliRunner()
    result = runner.invoke(orchestrator.app, ["--help"])
    assert result.exit_code == 0
    assert "--images" in result.output
    assert "--iterations" in result.output
